name: CI

on:
  pull_request:
  push:
    branches-ignore: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0    
    - name: Compile
      run: sbt clean +test