name: master

on:
  push:
    branches: [master]
    tags: ["*"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: olafurpg/setup-gpg@v3
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0   
    - name: Compile
      run: sbt clean +test 
    - name: Publish
      run: sbt -mem 3000 versionCheck ci-release
      env:
        PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
        PGP_SECRET: ${{ secrets.PGP_SECRET }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}   